services:
  postgres:
    image: postgres:16-alpine
    container_name: demo-admin-postgres
    environment:
      POSTGRES_DB: demo_admin
      POSTGRES_USER: demo_admin
      POSTGRES_PASSWORD: demo_admin
    ports:
      - "5432:5432"
    volumes:
      - demo-admin-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: demo-admin-redis
    ports:
      - "6379:6379"

volumes:
  demo-admin-postgres-data:
